services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=mkgg'
      - 'POSTGRES_DB=mkgg'
      - 'POSTGRES_PASSWORD=mkgg'
    volumes:
      - './volumes/mkgg/postgres:/var/lib/postgresql/data'
